# Generated by Django 4.0.5 on 2022-06-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
