# Generated by Django 4.0.5 on 2022-09-13 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_thing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
