# Generated by Django 4.0.5 on 2022-09-13 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_thing_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='date_updated',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
