# Generated by Django 4.0.5 on 2022-10-04 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_thing_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(auto_now_add=True)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fathered_children', to='tests.person')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mothered_children', to='tests.person')),
            ],
        ),
    ]
