# Generated by Django 4.0.5 on 2022-10-04 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_person_father_alter_person_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
